MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE : 1
  TRANS_USE : 1
  RES_MODE : 1
  SRM_LAYER : 2
  MIX_DIM : 768
  PRETRAIN_PATH_R : '/13994058190/WYH/PTH/resnet50-19c8e357.pth'
  PRETRAIN_PATH_T : '/13994058190/WYH/PTH/vitb_16_224_21k.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True


INPUT:
  SIZE_TRAIN: [ 384, 128 ]
  SIZE_TEST: [ 384, 128 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [ 0.5, 0.5, 0.5 ]
  PIXEL_STD: [ 0.5, 0.5, 0.5 ]

DATASETS:
  NAMES: ('dukemtmc')
  ROOT_DIR: '/13994058190/WYH/DATA/data_finetune/dukemtmc'

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './dukemtmc_vitb12_res50_layer2_384'

